// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB0JZJYkl86Eajnxp2mWCepbdVL46H8s2w',
    appId: '1:26856759116:web:ae5ff340f85a7c44a1b9e9',
    messagingSenderId: '26856759116',
    projectId: 'trainertrack-e6238',
    authDomain: 'trainertrack-e6238.firebaseapp.com',
    storageBucket: 'trainertrack-e6238.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDJE-BMGfTGFUvRkkK7Zfhr82EZSV_iCMY',
    appId: '1:26856759116:android:4ffbb0060fa5079ea1b9e9',
    messagingSenderId: '26856759116',
    projectId: 'trainertrack-e6238',
    storageBucket: 'trainertrack-e6238.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDv4_dy-uSq9FrrDCQIz9rOTAG_8fdHRN0',
    appId: '1:26856759116:ios:5f87e18681d4ad5ca1b9e9',
    messagingSenderId: '26856759116',
    projectId: 'trainertrack-e6238',
    storageBucket: 'trainertrack-e6238.firebasestorage.app',
    iosBundleId: 'com.example.trainerTrack2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDv4_dy-uSq9FrrDCQIz9rOTAG_8fdHRN0',
    appId: '1:26856759116:ios:5f87e18681d4ad5ca1b9e9',
    messagingSenderId: '26856759116',
    projectId: 'trainertrack-e6238',
    storageBucket: 'trainertrack-e6238.firebasestorage.app',
    iosBundleId: 'com.example.trainerTrack2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB0JZJYkl86Eajnxp2mWCepbdVL46H8s2w',
    appId: '1:26856759116:web:e9361bcf0f668d2fa1b9e9',
    messagingSenderId: '26856759116',
    projectId: 'trainertrack-e6238',
    authDomain: 'trainertrack-e6238.firebaseapp.com',
    storageBucket: 'trainertrack-e6238.firebasestorage.app',
  );
}
